# SPDX-FileCopyrightText: Alliander N. V.
# 
# SPDX-License-Identifier: Apache-2.0

services:
  franka:
    image: franka
    container_name: franka
    runtime: nvidia
    network_mode: host
    privileged: true
    mem_limit: 6gb
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "${HOME}/.vscode-server:${HOME}/.vscode-server"
      - "${HOME}/docker_ws:${HOME}/docker_ws"
      - "/dev:/dev"
    environment:
      - "DISPLAY"
      - "RCUTILS_COLORIZED_OUTPUT=1"
      - NVIDIA_VISIBLE_DEVICES=all
    tty: true
  mobile_manipulator:
    image: mobile_manipulator
    container_name: mobile_manipulator
    runtime: nvidia
    network_mode: host
    privileged: true
    mem_limit: 6gb
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "${HOME}/.vscode-server:${HOME}/.vscode-server"
      - "${HOME}/docker_ws:${HOME}/docker_ws"
      - "/dev/input:/dev/input"
    environment:
      - "DISPLAY"
      - "RCUTILS_COLORIZED_OUTPUT=1"
      - NVIDIA_VISIBLE_DEVICES=all
    tty: true
  panther:
    image: panther
    container_name: panther
    runtime: nvidia
    network_mode: host
    privileged: true
    mem_limit: 6gb
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "${HOME}/.vscode-server:${HOME}/.vscode-server"
      - "${HOME}/docker_ws:${HOME}/docker_ws"
      - "/dev/input:/dev/input"
    environment:
      - "DISPLAY"
      - "RCUTILS_COLORIZED_OUTPUT=1"
      - NVIDIA_VISIBLE_DEVICES=all
    tty: true
  ros2:
    image: ros2
    container_name: ros2
    runtime: nvidia
    network_mode: host
    privileged: true
    mem_limit: 6gb
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "${HOME}/.vscode-server:${HOME}/.vscode-server"
      - "${HOME}/docker_ws:${HOME}/docker_ws"
    environment:
      - "DISPLAY"
      - "RCUTILS_COLORIZED_OUTPUT=1"
      - NVIDIA_VISIBLE_DEVICES=all
    tty: true
